spring:
  application:
    name: familidge
  profiles:
    include:
    - infrastructure
    - env
  main:
    banner-mode: off
jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessTokenExpire: ${JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${JWT_REFRESH_EXPIRE}
